# Generated by Django 3.2.2 on 2021-10-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register_info',
        ),
    ]
