# Generated by Django 3.2.2 on 2021-11-07 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_register_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default='Hyderabad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
