# Generated by Django 3.2.2 on 2021-11-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211107_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
